[package]
name = "pig_latin"
version = "0.1.0"
authors = ["Ruchira Datta <Ruchira.Datta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unidecode = "0.3.0"
unicode-segmentation = "1.3.0"
